export * as Album from './Album'
export * as Comment from './Comment'
export * as Crud from './crud'
export * as Like from './Like'
export * as Photo from './Photo'
export * as PhotoOnAlbum from './PhotoOnAlbum'
export * as User from './User'
export * as UserOnAlbum from './UserOnAlbum'
